#include "containers.h"

const type_metadata meta[] = {
		[FT_VECTOR] = {
				.interface_type = FT_SEQUENCE_CONTAINER,
				.constructor = &ft_vector_default,
				.destructor = &ft_vector_destructor_wrapper,
				.copy = &ft_vector_copy,
				.container = {
						.begin = &ft_vector_begin,
						.end = &ft_vector_end,
						.clear = &ft_vector_clear,
						.erase_one = &ft_vector_erase_one,
						.erase_range = &ft_vector_erase_range,
						.sequence = {
								.push_front = &ft_vector_push_front,
								.push_back = &ft_vector_push_back,
								.push_front_ptr = &ft_vector_push_front_ptr,
								.push_back_ptr = &ft_vector_push_back_ptr,
								.pop_front = &ft_vector_pop_front,
								.pop_back = &ft_vector_pop_back,
								.insert_val	= &ft_vector_insert_val,
								.insert_range = &ft_vector_insert_range,
						},
				},
		},
		[FT_BHEAP] = {
				.interface_type = FT_SEQUENCE_CONTAINER,
				.constructor = &ft_vector_default,
				.destructor = &ft_vector_destructor_wrapper,
				.copy = &ft_vector_copy,
				.container = {
						.begin = &ft_vector_begin,
						.end = &ft_vector_end,
						.clear = &ft_vector_clear,
						.erase_one = &ft_vector_erase_one,
						.erase_range = &ft_vector_erase_range,
						.sequence = {
								.push_front = &ft_bheap_push,
								.push_back = &ft_bheap_push,
								.push_front_ptr = &ft_vector_push_front_ptr,
								.push_back_ptr = &ft_vector_push_back_ptr,
								.pop_front = &ft_bheap_pop,
								.pop_back = &ft_bheap_pop,
								.insert_val	= &ft_vector_insert_val,
								.insert_range = &ft_vector_insert_range,
						},
				},
		},
		[FT_LIST] = {
				.interface_type = FT_SEQUENCE_CONTAINER,
				.constructor = &ft_list_default,
				.destructor = &ft_list_destructor_wrapper,
				.copy = &ft_list_copy,
				.container = {
						.begin = &ft_list_begin,
						.end = &ft_list_end,
						.clear = &ft_list_clear,
						.erase_one = &ft_list_erase_one,
						.erase_range = &ft_list_erase_range,
						.sequence = {
								.push_front = &ft_push_front,
								.push_back = &ft_push_back,
								.pop_front = &ft_pop_front,
								.pop_back = &ft_pop_back,
								.insert_val	= &ft_list_insert_val,
								.insert_range = &ft_list_insert_range,
						},
				},
		},
		[FT_BST] = {
				.interface_type = FT_ASSOCIATIVE_CONTAINER,
				.constructor = &ft_bst_default,
				.destructor = &ft_bst_destructor_wrapper,
				.copy = &ft_bst_copy,
				.compare = &ft_bst_compare,
				.container = {
						.begin = &ft_bst_begin,
						.end = &ft_bst_end,
						.clear = &ft_bst_clear,
						.erase_one = &ft_bst_erase_one,
						.erase_range = &ft_erase_range,
						.associative = {
								.find = &ft_bst_find,
								.erase = &ft_erase_val,
								.insert = ft_bst_insert_val,
						},
				},
		},
};